name: "kafka-spout-word-count"
config:
  topology.workers: ${topology.workers}

components:
  - id: "zkHosts"
    className: "org.apache.storm.kafka.ZkHosts"
    constructorArgs:
      - "${kafka.zookeeper.connect}"
      - "${kafka.zookeeper.paths}"

  - id: "stringMultiSchemeWithTopic"
    className: "org.apache.storm.kafka.StringMultiSchemeWithTopic"

  - id: "startingOffsetTime"
    className: "kafka.api.OffsetRequest"
    factory: "LatestTime"

  - id: "spoutConfig"
    className: "org.apache.storm.kafka.SpoutConfig"
    constructorArgs:
      # brokerHosts
      - ref: "zkHosts"
      # topic
      - "${kafka.consumer.topics}"
      # zkRoot
      - "${kafka.zookeeper.zkRoot}"
      # id
      - "${kafka.consumer.progress.id}"
    properties:
      - name: "ignoreZkOffsets"
        value: false
      - name: "scheme"
        ref: "stringMultiSchemeWithTopic"
      - name: "zkServers"
        value: ${kafka.zookeeper.hosts}
      - name: "zkPort"
        value: ${kafka.zookeeper.port}
      - name: "startOffsetTime"
        ref: "startingOffsetTime"


# spout定义
spouts:
  - id: "spout-kafka-sentence"
    parallelism: 1
    className: "org.apache.storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "spoutConfig"

# bolt定义
bolts:
  - id: "bolt_split"
    className: "org.roc.storm.wordcount.bolt.SplitSentenceBolt"
    parallelism: ${bolt_split.parallelism}

  - id: "bolt_word_count"
    className: "org.roc.storm.wordcount.bolt.WordCount"
    parallelism: ${bolt_word_count.parallelism}

  - id: "bolt_logger"
    className: "org.roc.storm.wordcount.bolt.LogInfoBolt"
    parallelism: ${bolt_logger.parallelism}

# stream定义
streams:
#name暂时未用上（可以在logging,UI等中作为placeholder）
  - name: "spout-kafka-sentence --> bolt_split"
    from: "spout-kafka-sentence"
    to: "bolt_split"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - name: "bolt_split --> bolt_word_count"
    from: "bolt_split"
    to: "bolt_word_count"
    grouping:
      type: FIELDS
      args: ["word"]

  - name: "bolt_word_count --> bolt_logger"
    from: "bolt_word_count"
    to: "bolt_logger"
    grouping:
      type: LOCAL_OR_SHUFFLE
