name: "jdbc-word-count"
config:
  topology.workers: ${topology.workers}


components:
  - id: "hikariConfig"
    className: "java.util.HashMap"
    configMethods:
      - name: "put"
        args:
          - "dataSourceClassName"
          - "${data.source.class.name}"
      - name: "put"
        args:
          - "dataSource.url"
          - "${data.source.url}"
      - name: "put"
        args:
          - "dataSource.user"
          - "${data.source.user}"
      - name: "put"
        args:
          - "dataSource.password"
          - "${data.source.password}"

  - id: "connectionProvider"
    className: "org.apache.storm.jdbc.common.HikariCPConnectionProvider"
    constructorArgs:
      - ref: "hikariConfig"


# spout定义
spouts:
  - id: "spout_sentence"
    className: "org.roc.storm.wordcount.spout.RandomSentenceSpout"
    parallelism: ${spout.sentence.parallelism}

# bolt定义
bolts:
  - id: "bolt_split"
    className: "org.roc.storm.wordcount.bolt.SplitSentenceBolt"
    parallelism: ${bolt.split.parallelism}

  - id: "bolt_word_count"
    className: "org.roc.storm.wordcount.bolt.WordCount"
    parallelism: ${bolt.word.count.parallelism}

  - id: "bolt_jdbc_insert"
    className: "org.roc.storm.jdbc.bolt.TableJdbcInsertBolt"
    parallelism: ${bolt.jdbc.insert.parallelism}
    constructorArgs:
      - ref: "connectionProvider"
    configMethods:
      - name: "withQueryTimeoutSecs"
        args:
          - ${query.timeout.seconds}

# stream定义
streams:
#name暂时未用上（可以在logging,UI等中作为placeholder）
  - name: "spout_sentence --> bolt_split"
    from: "spout_sentence"
    to: "bolt_split"
    grouping:
      type: LOCAL_OR_SHUFFLE

  - name: "bolt_split --> bolt_word_count"
    from: "bolt_split"
    to: "bolt_word_count"
    grouping:
      type: FIELDS
      args: ["word"]

  - name: "bolt_word_count --> bolt_jdbc_insert"
    from: "bolt_word_count"
    to: "bolt_jdbc_insert"
    grouping:
      type: LOCAL_OR_SHUFFLE
